import express from "express";
import UsersRouter from "./UsersRouter.js";
import ProductsRouter from "./ProductRouter.js";
import CartRouter from "./CartRouter.js";
import CategoryRouter from "./CategoryRouter.js";
import SearchRouter from "./SearchRouter.js";
const router = express.Router();
router.use("/users", UsersRouter);
router.use("/Products", ProductsRouter);
router.use("/Cart", CartRouter);
router.use("/Category", CategoryRouter);
router.use("/Search", SearchRouter);
export default router;
